name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # - uses: purescript-contrib/setup-purescript@main
      - uses: srghma/setup-purescript@main
        with:
          purescript: "latest"
          psa: "latest"
          spago: "unstable"
          purs-tidy: "latest"
      - uses: actions/cache@v2
        # This cache uses the .dhall files to know when it should reinstall
        # and rebuild packages. It caches both the installed packages from
        # the `.spago` directory and compilation artifacts from the `output`
        # directory. When restored the compiler will rebuild any files that
        # have changed.
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/*.dhall') }}
          path: |
            .spago
            output

      - name: Build source
        run: spago build --pedantic-packages

      - name: Run tests
        run: npm test

      - name: Verify formatting
        run: purs-tidy check src test
